services:
  - type: web
    name: sec-downloader
    env: python
    plan: free
    buildCommand: apt-get update && apt-get install -y libpango-1.0-0 libpangoft2-1.0-0 libharfbuzz0b libfontconfig1 libcairo2 libgdk-pixbuf2.0-0 && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 120
